#!/bin/bash

##################################################
#                                                #
#       Team BlueRidge Gerrit push script.       #
# Pushes to http://gerrit.teamblueridge.com:8080 #
#     Created by: kalaker and simonsimons34      #
#               License: GNU GPLv2               #
#                                                #
##################################################

#Initial un/variable figuring out
clear
project=$2
branch=$3
name="Team BlueRidge Gerrit"
url="http://gerrit.teamblueridge.com/"
if [ -f ~/.ssh/tbr_username ]
then
    un=`cat ~/.ssh/tbr_username`
    echo "Welcome back to $name, $un!"
    echo "You've already been through setup already so let's continue!"
    echo "Your username is ${un}. To change this, execute 'rm -rf ~/.ssh/tbr_username'."
else
    echo "Welcome to $name"
    echo "You need to setup your account."
    echo "If you don't have a $name account, please go to $url and create one."
    echo -n "What is your $name username: "
    read un
    echo $un > ~/.ssh/tbr_username
    echo "Your username is ${un}. To change this, execute 'rm -rf ~/.ssh/tbr_username'."
    echo "BE SURE YOUR SSH KEYS ARE MATCHED WITH GERRIT IN YOUR SETTINGS"
fi


#Begin Functions
function yes () {
if [ -z "$2" ]
then
    echo "Project name not given.";
    read -p "Project name (case-sensitive): " project
fi
if [ -z "$3" ]
then
    echo "Branch wname not given."
    read -p "Branch name (case-sensitive): " branch
fi
un=`cat ~/.ssh/tbr_username`
git push "ssh://$un@gerrit.teamblueridge.com:29418/$project" "HEAD:refs/for/$branch"
echo "Push successful"
exit 0
}

function regular () {
if [ -z "$1" ]
then
echo "Project name not given.";
read -p "Project name (case-sensitive): " project
else
project=$1
fi
if [ -z "$2" ]
then
echo "Branch wname not given."
read -p "Branch name (case-sensitive): " branch
else
branch=$2
fi
un=`cat ~/.ssh/tbr_username`
while true
do
read -p "Have you already committed your changes [Y/N]? " yn
case $yn in
[Yy]* ) echo "Good, let's continue"; break;;
[Nn]* ) echo "Please commit your changes ('git commit -a') then start again."; exit 1;;
* ) echo "Please answer Yes or No.";;
esac
done
echo "Push information:"
echo "Your username: $un"
echo "Project: $project"
echo "Branch: $branch"
while true
do
read -p "Are you sure you wish to push to Gerrit [Y/N]? " yn
case $yn in
[Yy]* ) git push "ssh://$un@gerrit.teamblueridge.com:29418/$project" "HEAD:refs/for/$branch"; echo "Push successful"; break;;
[Nn]* ) echo "Goodbye."; exit 1;;
* ) echo "Please answer Yes or No.";;
esac
done
exit 0
}

function help () {
echo "Usage:    './gerrit.sh [-y] [<project> [<branch>]]'"
echo "-y        Responds \"Y\" to all questions"
echo "<project> Project that is being committed to"
echo "<branch>  Branch that is being commited to"
echo "<project> must be included if <branch> is"
exit 0
}

function info () {
echo "Current path: `pwd`"
echo "Username: `cat ~/.ssh/tbr_username`"
exit 0
}


#Options available
while :
 do
    case $1 in
        -y | -Y | --yes )
            yes
        ;;
        -i | --info )
            info
        ;;
        -h | --help | -* )
            help
        ;;
        * )
            regular
        ;;
    esac
  done
exit 0
